import Head from "next/head";
import { Header } from "@/features/header/components/Header";
import { HeroSection } from "@/features/home/components/HeroSecion";
import FeaturesList from "@/features/home/components/FeaturesList";
import DiaryPreview from "@/features/home/components/DiaryPreview";
import EnrollmentBanner from "@/features/home/components/EnrollmentBanner";
import Footer from "@/features/footer/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <FeaturesList />
      <DiaryPreview />
      <EnrollmentBanner />
      <Footer />
    </>
  );
}
